### PR TITLE
feat: add react-native nominees

### PR DESCRIPTION
**Pull request by jayu**

### CODE REVIEW

**Comment by robhrt7** [comment]
Hey @jaysbytes, please add all the images to the repo, instead of external links.

**Comment by jayu** [comment]
Hey @operatino, Done :)

**Comment by jayu** [comment]
Hi @operatino ! Is there everything OK with deploy job? We cannot see changes on https://osawards.com/reactnative/

**Comment by robhrt7** [comment]
@jaysbytes looking into it

**Pull request merged**
