### PR TITLE
Add 2019 Javascript Nominees

### PR DESCRIPTION
**Pull request by iamchathu**

### CODE REVIEW

**Comment by iamchathu** [comment]
@operatino There is issue with jQuery when there is previous nominees list. It break styles because of the href link. So for now I commented it out.

**Comment by robhrt7** [comment]
@iamchathu please align the code with React page, it did not had issues

**Comment by iamchathu** [comment]
Links wan't there early. It was formatted to my VSCode formatting. Can I get old editor configurations. .editorconfig was added by myself.

**Comment by robhrt7** [comment]
React sub-page works with no issues, right? The structure of sub-pages is the same, so you can copy scripts and etc. 

As for editor config - we don't have any specific, you can use the same as on React sub-page.

**Comment by iamchathu** [comment]
@operatino It works in React subpages and I copied also tried a diff too. But couldn't find a cause. Will try again on it. Will explore to find what is the config of react pages. In react pages I didn't format HTML. But for these pages I have enabled auto format on save.

**Comment by iamchathu** [comment]
@operatino After adding react folder `scripts.js` to javascript issue got fixed.

**Comment by robhrt7** [comment]
Thanks a lot, @iamchathu!

**Pull request merged**
